# Generated by Django 4.1.7 on 2023-02-16 23:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('altitude', models.CharField(max_length=20)),
                ('ebikes', models.BigIntegerField()),
                ('has_bikes', models.BooleanField()),
                ('last_updated', models.BigIntegerField()),
                ('normal_bikes', models.BigIntegerField()),
                ('payment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('payment_terminal', models.BooleanField()),
                ('post_code', models.CharField(blank=True, max_length=200, null=True)),
                ('renting', models.BigIntegerField()),
                ('returning', models.BigIntegerField()),
                ('slots', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('latitude', models.CharField(max_length=40)),
                ('longitude', models.CharField(max_length=40)),
                ('free_bikes', models.BigIntegerField()),
                ('empty_slots', models.BigIntegerField()),
                ('extra', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bike.extra')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('gbfs_href', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('location', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bike.location')),
                ('stations', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bike.stations')),
            ],
        ),
    ]
