# Generated by Django 4.1.7 on 2023-02-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='post_code',
        ),
    ]
