# Generated by Django 4.1.7 on 2023-02-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_remove_extra_post_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stations',
            name='extra',
        ),
    ]
