# Generated by Django 4.1.7 on 2023-02-17 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_remove_stations_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='location',
        ),
        migrations.RemoveField(
            model_name='network',
            name='stations',
        ),
    ]
