# Generated by Django 4.1.7 on 2023-02-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('document_type', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('typology', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=200)),
                ('investment', models.DecimalField(decimal_places=4, max_digits=5)),
                ('presentation_date', models.DateField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
