# Generated by Django 4.1.7 on 2023-02-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='investment',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
