# Generated by Django 4.1.7 on 2023-02-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0002_alter_project_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='investment',
            field=models.CharField(max_length=2000),
        ),
    ]
